#pragma config(Motor,  port2,           rightWheel,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftWheel,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           netMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           sliderMotor,   tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "actions.c"

task main()
{
	StartTask(drive);
	StartTask(net);
	StartTask(slider);

	while(true);
}
