#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           grabMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           shootServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "actions.c"

task main()
{
	startTask(drive);
	startTask(shoot);
	startTask(arcadeDrive);
	startTask(grabber);
	while(1);
}
