#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port4,           doorServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Include the other files necessary for the program
#include "config.h"
#include "drive.c"
#include "actions.c"

task main()
{
	// Run the start-up actions to get the robot ready (see actions.c)
	init();

	// Start taking input from the driver for moving (see drive.c)
	startTask(drive);

	// Run the moveable door
	while(true){
		// Only if the DOOR_BTN is pressed down
		if(vexRT[DOOR_BTN]){
			// Call the toggle_door method (in actions.c)
			toggle_door();
		}
	}
}
