#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, driveLeft)
<<<<<<< HEAD
#pragma config(Motor,  port3,           dustPan,       tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port4,           doorServo,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           forkLift,      tmotorServoContinuousRotation, openLoop, driveRight)
=======
#pragma config(Motor,  port3,           forkliftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           dustpanMotor,  tmotorServoContinuousRotation, openLoop)
>>>>>>> 30761cac855f0f53cdd4b99819748e904a24f9f9
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Include the other files necessary for the program
#include "config.h"
#include "drive.c"
#include "actions.c"

// Run the main task: starts the other tasks and controls the back door
task main()
{
	// Runs the start-up actions (see actions.c)
	init();

	// Starts taking input from the driver for moving (see drive.c)
	startTask(drive);

	startTask(dustpan);

<<<<<<< HEAD
	startTask(fork_lift);

	// Runs the moveable door
=======
	// Runs the forklift
>>>>>>> 30761cac855f0f53cdd4b99819748e904a24f9f9
	while(true){
		motor[forkliftMotor] = (vexRT[FORKLIFT_UP] - vexRT[FORKLIFT_DOWN]) * BTN_SPEED;
	}
}
