#pragma config(Motor,  port2,           rightWheel,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftWheel,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           rollerMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           sweeperMotor,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           waterServoCont, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "actions.c"

task main()								// The main task of the robot that calls all the other tasks
{
	startTask(drive);				// Starts the drive task (for the wheels of the robot)
	startTask(roller);			// Starts the roller task (for the roller attache to the robot)
	startTask(sweeper);			// Starts the sweeper task (for the rotating sweeper in the front)
	startTask(water_servo); // Starts the water valve servo task (for turning the water valve)

	while(true);						// Don't want to let the program end before the robot is shut down
}
