#pragma config(Motor,  port2,           rightWheel,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftWheel,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           netMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           sweeperMotor,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           waterServoCont, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "actions.c"

task main()			// The main task of the robot that calls all the other tasks
{
	StartTask(drive);	// Starts the drive task (for the wheels of the robot)
	StartTask(net);		// Starts the net task (for the net attache to the robot)
	StartTask(sweeper);	// Starts the sweeper task (for the rotating sweeper in the front)

	while(true);		// Don't want to let the program end before the robot is shut down
}
