#pragma config(Motor,  port2,           rightWheel,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftWheel,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           seedServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "actions.c"

task main()								// The main task of the robot that calls all the other tasks
{
	startTask(drive);				// Starts the drive task (for the wheels of the robot)
	startTask(seeds);				// Runs the servo for the seed depositer

	while(true);						// Don't want to let the program end before the robot is shut down
}
