#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           grabMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           shootServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.h"
#include "actions.c"

task main()
{
	//Initiates tasks
	startTask(drive);		// Robot drive task
	startTask(shoot);		// Robot shooter task
	startTask(grabber); // Robot grabber task
	startTask(claw);		// Robot claw task
	while(1);	//Makes sure that robot does not shut off
}
